### ISSUE TITLE
点击目录后，会立刻跳转到指定目录的锚点，然后会慢慢向上又滚回目录起点,是什么问题？

### ISSUE THREAD

**Issue by javaerschoolcom** [KELEN/katelog#4]
点击目录后，会立刻跳转到指定目录的锚点，然后会慢慢向上又滚回目录,是什么问题？我用的是vue,没有引入jquery有影响？

**Comment by KELEN** [comment]
嗯，不需要引入jquery，这个是每次点击目录都会触发这种情况吗？

**Comment by javaerschoolcom** [comment]
问题解决了，目录我设置成position:fixed就好了。多谢

**Comment by KELEN** [comment]
fixed
